Repository zattoo/changelog, pull requests merged in 2020-12, with the labels that each got.

#41 Release
  .eslintrc.js
  CHANGELOG.md
  dist/index.js
  package-lock.json
  package.json
  src/files.js
  src/index.js
  src/release.js
  src/validate.js
Labels: release

#42 Backmerge
  CHANGELOG.md
  dist/index.js
  package-lock.json
  package.json
  src/files.js
Labels: infrastructure

#43 Hotfix 1.6.1
  CHANGELOG.md
  dist/index.js
  package-lock.json
  package.json
  src/index.js
Labels: bug, hotfix

#44 z-merge.yml
  .github/workflows/z-merge.yml
  CHANGELOG.md
Labels: infrastructure
