Repository zattoo/changelog, pull requests merged in 2020-07, with the labels that each got.

#21 Array sources
  README.md
  action.yml
  dist/index.js
  src/index.js
Labels: enhancement

#22 Changelog Validate
  .github/workflows/CODEOWNERS
  .github/workflows/main.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  action.yml
  package-lock.json
  package.json
  src/index.js
Labels: bug, documentation, enhancement

#26 Support glob in sources
  CHANGELOG.md
  dist/index.js
  package-lock.json
  package.json
  src/files.js
  src/index.js
Labels: feature
